import { SQLDatabase } from "encore.dev/storage/sqldb";
import { PrismaClient } from "@prisma/client";

// Define a database named 'encore_prisma_test', using the database migrations
// in the "./prisma/migrations" folder (where prisma will generate their migrations).
// Set `source` to `prisma` to let Encore know that the migrations are generated by Prisma.
const DB = new SQLDatabase("cooking_app", {
  migrations: {
    path: "./prisma/migrations",
    source: "prisma",
  },
});

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: "postgresql://postgres.izzqtyfeylanzkrpzdom:cooking-app@123@aws-0-ap-south-1.pooler.supabase.com:5432/postgres",
    },
  },
});

export { prisma };
